#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir=$install_dir

chmod +x $install_dir/app.js

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Collaborative Markdown notes" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="config.json.example" --destination="$install_dir/config.json"
ynh_config_add --template=".sequelizerc.example" --destination="$install_dir/.sequelizerc"

chmod 600 $install_dir/.sequelizerc

#=================================================
# INSTALL CODIMD
#=================================================
ynh_script_progression "Building $app... (this will take some time and resources!)"

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app bin/setup
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start --log_path=systemd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
