#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir=$install_dir --keep="config.json .sequelizerc"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

ynh_nodejs_install

#==============================================
# INSTALL CODIMD
#==============================================
ynh_script_progression "Building CodiMD... (this will take some time and resources!)"

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app bin/setup
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Collaborative Markdown notes" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start --log_path=systemd --wait_until="HTTP Server listening"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
